-- Add furigana_html column to lines table
-- Auto-generated by kuroshiro after Japanese lines are saved.
-- Not bumped via updated_at to avoid triggering sync conflicts.

ALTER TABLE lines ADD COLUMN IF NOT EXISTS furigana_html text;
