/**
 * google-drive-auth
 * Redirects the user to Google's OAuth consent page.
 * Called by the mobile app: open this URL in a browser.
 *
 * Query params:
 *   state — opaque string generated by the app (CSRF protection)
 */
const CLIENT_ID = Deno.env.get("GOOGLE_DRIVE_CLIENT_ID")!;
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const CALLBACK_URL = `${SUPABASE_URL}/functions/v1/google-drive-callback`;

const GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth";

Deno.serve((req: Request) => {
  const url = new URL(req.url);
  const state = url.searchParams.get("state") ?? "";

  const authUrl = new URL(GOOGLE_AUTH_URL);
  authUrl.searchParams.set("client_id", CLIENT_ID);
  authUrl.searchParams.set("redirect_uri", CALLBACK_URL);
  authUrl.searchParams.set("response_type", "code");
  authUrl.searchParams.set("scope", "https://www.googleapis.com/auth/drive.file");
  authUrl.searchParams.set("access_type", "offline");
  authUrl.searchParams.set("prompt", "consent");
  authUrl.searchParams.set("state", state);

  return Response.redirect(authUrl.toString(), 302);
});
